# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './modules/Dash/design.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DashForm(object):
    def setupUi(self, DashForm):
        DashForm.setObjectName("DashForm")
        DashForm.resize(905, 524)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DashForm.sizePolicy().hasHeightForWidth())
        DashForm.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(DashForm)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelMemInfo = QtWidgets.QLabel(DashForm)
        self.labelMemInfo.setObjectName("labelMemInfo")
        self.gridLayout.addWidget(self.labelMemInfo, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lcdCpu = QtWidgets.QLCDNumber(DashForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdCpu.sizePolicy().hasHeightForWidth())
        self.lcdCpu.setSizePolicy(sizePolicy)
        self.lcdCpu.setMinimumSize(QtCore.QSize(0, 150))
        self.lcdCpu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdCpu.setSmallDecimalPoint(False)
        self.lcdCpu.setDigitCount(2)
        self.lcdCpu.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdCpu.setObjectName("lcdCpu")
        self.gridLayout.addWidget(self.lcdCpu, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(DashForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.systemInfo = QtWidgets.QTextBrowser(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.systemInfo.sizePolicy().hasHeightForWidth())
        self.systemInfo.setSizePolicy(sizePolicy)
        self.systemInfo.setObjectName("systemInfo")
        self.gridLayout_2.addWidget(self.systemInfo, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 2)
        self.lcdMem = QtWidgets.QLCDNumber(DashForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMem.sizePolicy().hasHeightForWidth())
        self.lcdMem.setSizePolicy(sizePolicy)
        self.lcdMem.setDigitCount(2)
        self.lcdMem.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdMem.setObjectName("lcdMem")
        self.gridLayout.addWidget(self.lcdMem, 0, 1, 1, 1)
        self.lcdDisk = QtWidgets.QLCDNumber(DashForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdDisk.sizePolicy().hasHeightForWidth())
        self.lcdDisk.setSizePolicy(sizePolicy)
        self.lcdDisk.setDigitCount(2)
        self.lcdDisk.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdDisk.setObjectName("lcdDisk")
        self.gridLayout.addWidget(self.lcdDisk, 0, 2, 1, 1)
        self.labelCpuInfo = QtWidgets.QLabel(DashForm)
        self.labelCpuInfo.setObjectName("labelCpuInfo")
        self.gridLayout.addWidget(self.labelCpuInfo, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.labelDiskInfo = QtWidgets.QLabel(DashForm)
        self.labelDiskInfo.setObjectName("labelDiskInfo")
        self.gridLayout.addWidget(self.labelDiskInfo, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_network = QtWidgets.QLabel(DashForm)
        self.label_network.setObjectName("label_network")
        self.verticalLayout.addWidget(self.label_network)
        self.horizontalWidget = QtWidgets.QWidget(DashForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.horizontalWidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5, 0, QtCore.Qt.AlignRight)
        self.lcdNetIn = QtWidgets.QLCDNumber(self.horizontalWidget)
        self.lcdNetIn.setSmallDecimalPoint(False)
        self.lcdNetIn.setDigitCount(6)
        self.lcdNetIn.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNetIn.setObjectName("lcdNetIn")
        self.horizontalLayout_4.addWidget(self.lcdNetIn)
        self.label_2 = QtWidgets.QLabel(self.horizontalWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout.addWidget(self.horizontalWidget)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalWidget1 = QtWidgets.QWidget(DashForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget1.sizePolicy().hasHeightForWidth())
        self.horizontalWidget1.setSizePolicy(sizePolicy)
        self.horizontalWidget1.setObjectName("horizontalWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.horizontalWidget1)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4, 0, QtCore.Qt.AlignRight)
        self.lcdNetOut = QtWidgets.QLCDNumber(self.horizontalWidget1)
        self.lcdNetOut.setDigitCount(6)
        self.lcdNetOut.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNetOut.setObjectName("lcdNetOut")
        self.horizontalLayout_5.addWidget(self.lcdNetOut)
        self.label_3 = QtWidgets.QLabel(self.horizontalWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 3)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout.addWidget(self.horizontalWidget1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.gridLayout.addLayout(self.verticalLayout, 2, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(DashForm)
        QtCore.QMetaObject.connectSlotsByName(DashForm)

    def retranslateUi(self, DashForm):
        _translate = QtCore.QCoreApplication.translate
        DashForm.setWindowTitle(_translate("DashForm", "Form"))
        self.labelMemInfo.setText(_translate("DashForm", "Loading..."))
        self.lcdCpu.setToolTip(_translate("DashForm", "CPU"))
        self.label.setText(_translate("DashForm", "System Information"))
        self.lcdMem.setToolTip(_translate("DashForm", "Memory"))
        self.lcdDisk.setToolTip(_translate("DashForm", "Disk"))
        self.labelCpuInfo.setText(_translate("DashForm", "Loading..."))
        self.labelDiskInfo.setText(_translate("DashForm", "Loading..."))
        self.label_network.setText(_translate("DashForm", "Network Static"))
        self.label_5.setText(_translate("DashForm", "Input"))
        self.label_2.setText(_translate("DashForm", "KB/S"))
        self.label_4.setText(_translate("DashForm", "Output"))
        self.label_3.setText(_translate("DashForm", "KB/S"))

