# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1128, 686)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.sidebar = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar.sizePolicy().hasHeightForWidth())
        self.sidebar.setSizePolicy(sizePolicy)
        self.sidebar.setMinimumSize(QtCore.QSize(60, 0))
        self.sidebar.setMaximumSize(QtCore.QSize(60, 16777215))
        self.sidebar.setStyleSheet("")
        self.sidebar.setObjectName("sidebar")
        self.sidebarLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.sidebarLayout.setContentsMargins(0, 5, 0, 5)
        self.sidebarLayout.setSpacing(0)
        self.sidebarLayout.setObjectName("sidebarLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.sidebarLayout.addItem(spacerItem)
        self.btnDash = QtWidgets.QPushButton(self.sidebar)
        self.btnDash.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDash.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnDash.setStyleSheet("")
        self.btnDash.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/img/sidebar-icons/dash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDash.setIcon(icon)
        self.btnDash.setIconSize(QtCore.QSize(35, 35))
        self.btnDash.setCheckable(True)
        self.btnDash.setChecked(True)
        self.btnDash.setObjectName("btnDash")
        self.sidebarLayout.addWidget(self.btnDash)
        self.btnStartups = QtWidgets.QPushButton(self.sidebar)
        self.btnStartups.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStartups.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnStartups.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/img/sidebar-icons/startup-apps.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStartups.setIcon(icon1)
        self.btnStartups.setIconSize(QtCore.QSize(35, 35))
        self.btnStartups.setCheckable(True)
        self.btnStartups.setObjectName("btnStartups")
        self.sidebarLayout.addWidget(self.btnStartups)
        self.btnProcesses = QtWidgets.QPushButton(self.sidebar)
        self.btnProcesses.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnProcesses.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnProcesses.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/img/sidebar-icons/process.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnProcesses.setIcon(icon2)
        self.btnProcesses.setIconSize(QtCore.QSize(35, 35))
        self.btnProcesses.setCheckable(True)
        self.btnProcesses.setObjectName("btnProcesses")
        self.sidebarLayout.addWidget(self.btnProcesses)
        self.btnResource = QtWidgets.QPushButton(self.sidebar)
        self.btnResource.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnResource.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnResource.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/img/sidebar-icons/resources.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnResource.setIcon(icon3)
        self.btnResource.setIconSize(QtCore.QSize(35, 35))
        self.btnResource.setCheckable(True)
        self.btnResource.setObjectName("btnResource")
        self.sidebarLayout.addWidget(self.btnResource)
        self.btnSetup = QtWidgets.QPushButton(self.sidebar)
        self.btnSetup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSetup.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSetup.setStyleSheet("")
        self.btnSetup.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("assets/img/sidebar-icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSetup.setIcon(icon4)
        self.btnSetup.setIconSize(QtCore.QSize(35, 35))
        self.btnSetup.setCheckable(True)
        self.btnSetup.setObjectName("btnSetup")
        self.sidebarLayout.addWidget(self.btnSetup)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.sidebarLayout.addItem(spacerItem1)
        self.btnDash.raise_()
        self.btnSetup.raise_()
        self.btnResource.raise_()
        self.btnStartups.raise_()
        self.btnProcesses.raise_()
        self.rightWidget = QtWidgets.QWidget(self.splitter)
        self.rightWidget.setObjectName("rightWidget")
        self.mainLayout = QtWidgets.QGridLayout(self.rightWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setObjectName("mainLayout")
        self.mainWidgetLabel = QtWidgets.QLabel(self.rightWidget)
        self.mainWidgetLabel.setScaledContents(False)
        self.mainWidgetLabel.setObjectName("mainWidgetLabel")
        self.mainLayout.addWidget(self.mainWidgetLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.mainWidget = QtWidgets.QWidget(self.rightWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWidget.sizePolicy().hasHeightForWidth())
        self.mainWidget.setSizePolicy(sizePolicy)
        self.mainWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.mainWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.mainWidget.setBaseSize(QtCore.QSize(0, 0))
        self.mainWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.mainWidget.setObjectName("mainWidget")
        self.mainLayout.addWidget(self.mainWidget, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btnDash.clicked.connect(MainWindow.selectPage)
        self.btnStartups.clicked.connect(MainWindow.selectPage)
        self.btnProcesses.clicked.connect(MainWindow.selectPage)
        self.btnResource.clicked.connect(MainWindow.selectPage)
        self.btnSetup.clicked.connect(MainWindow.selectPage)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Linuxer"))
        self.btnDash.setToolTip(_translate("MainWindow", "Dashboard"))
        self.btnStartups.setToolTip(_translate("MainWindow", "Starup Services"))
        self.btnProcesses.setToolTip(_translate("MainWindow", "Processes"))
        self.btnResource.setToolTip(_translate("MainWindow", "Resouce Chart"))
        self.btnSetup.setToolTip(_translate("MainWindow", "Application Setups"))
        self.mainWidgetLabel.setText(_translate("MainWindow", "System Dash Board"))

